import React from 'react';
import { Mafs, Coordinates, Plot, Text, Point, Polyline } from 'mafs';

export default function Graph({
  title,
  result,
  fx,
  xPoints,
  fxPoints,
  benchmark,
  isRomberg,
}) {
  // Title: Ex: Simpson's Rule
  // Result: Result of the integral
  // fx: Function to be integrated
  // xPoints: Array of x points
  // fxPoints: Array of y points generated by integration method
  // benchmark: Time taken to calculate the integral
  // isRomberg: Boolean to check if the method is Romberg

  return (
    <Mafs viewBox={{ x: [-10, 10], y: [-10, 10] }} preserveAspectRatio={false}>
      <Coordinates.Cartesian subdivisions={4} />

      <Plot.OfX
        y={(x) => {
          try {
            return fx.evaluate({ x: x });
          } catch {
            return NaN;
          }
        }}
      />

      <Text x={-5} y={5}>
        {title}
      </Text>

      <Text x={5} y={5}>
        Result: {result}
      </Text>

      <Text x={-5} y={-5}>
        Benchmark: {benchmark}
      </Text>

      {isRomberg && (
        <Polyline
          points={xPoints.map((x, i) => [x, fxPoints[i]])}
          color="blue"
        />
      )}

      {xPoints.map((point, i) => (
        <Point key={i} x={point} y={fxPoints[i]} />
      ))}
    </Mafs>
  );
}
